#!/usr/bin/env python3
"""
Embed cursors/*.png as C++ byte arrays into a generated .cpp file.
Usage: embed_cursors.py <cursors_dir> <output.cpp>
"""
import os
import sys

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("Usage: embed_cursors.py <cursors_dir> <output.cpp>\n")
        sys.exit(1)
    cursors_dir = sys.argv[1]
    out_path = sys.argv[2]

    pngs = sorted(f for f in os.listdir(cursors_dir) if f.endswith('.png'))
    if not pngs:
        sys.stderr.write("No .png files in %s\n" % cursors_dir)
        sys.exit(1)

    lines = []
    lines.append("/* AUTO-GENERATED by embed_cursors.py - do not edit */")
    lines.append("#include \"cursor_assets.h\"")
    lines.append("#include <cstring>")
    lines.append("")

    table_entries = []
    for f in pngs:
        path = os.path.join(cursors_dir, f)
        with open(path, "rb") as fp:
            data = fp.read()
        base = os.path.splitext(f)[0].replace("-", "_")
        var = base + "_png"
        len_var = base + "_png_len"
        lines.append("static const unsigned char %s[] = {" % var)
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            hexs = ", ".join("0x%02xu" % b for b in chunk)
            lines.append("  " + hexs + ",")
        lines.append("};")
        lines.append("static const size_t %s = %du;" % (len_var, len(data)))
        lines.append("")
        table_entries.append('  { "%s", %s, %s }' % (f, var, len_var))

    lines.append("static const CursorAsset g_cursor_assets[] = {")
    lines.append(",\n".join(table_entries))
    lines.append("};")
    lines.append("")
    lines.append("int get_cursor_asset_count(void) { return (int)(sizeof(g_cursor_assets) / sizeof(g_cursor_assets[0])); }")
    lines.append("const CursorAsset *get_cursor_assets(void) { return g_cursor_assets; }")
    lines.append("")
    lines.append("const CursorAsset *get_cursor_asset_by_name(const char *filename) {")
    lines.append("  const CursorAsset *a = g_cursor_assets;")
    lines.append("  int n = get_cursor_asset_count();")
    lines.append("  for (int i = 0; i < n; i++, a++)")
    lines.append('    if (filename && a->filename && strcmp(a->filename, filename) == 0)')
    lines.append("      return a;")
    lines.append("  return nullptr;")
    lines.append("}")

    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w") as fp:
        fp.write("\n".join(lines) + "\n")

if __name__ == "__main__":
    main()
